[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "takt"
author = "Max Greco <mmngreco@gmail.com>"
author-email = "mmngreco@gmail.com"
home-page = "https://github.com/mmngreco/takt"
description-file = "README.md"
requires = ["rich", "typer"]
requires-python = ">=3.6"
license = "MIT"

[tool.flit.scripts]
takt = "takt:takt"

